// data.js

const nodesData = [
    { id: 'Peter Seah', label: 'Peter Seah', shape: 'ellipse', hidden: true },
    { id: 'Goh Choon Phong', label: 'Goh Choon Phong', shape: 'ellipse', hidden: true },
    { id: 'Simon Cheong', label: 'Simon Cheong', shape: 'ellipse', hidden: true },
    { id: 'David John', label: 'David John', shape: 'ellipse', hidden: true },
    { id: 'Dominic Ho', label: 'Dominic Ho', shape: 'ellipse', hidden: true },
    { id: 'Jeanette Wong', label: 'Jeanette Wong', shape: 'ellipse', hidden: true },
    { id: 'Yeoh Oon Jin', label: 'Yeoh Oon Jin', shape: 'ellipse', hidden: true },
    { id: 'Kai Yuan Wong', label: 'Kai Yuan Wong', shape: 'ellipse', hidden: true },
    { id: 'David Gledhill', label: 'David Gledhill', shape: 'ellipse', hidden: true },
    { id: 'Singtel', label: 'Singtel', shape: 'box' },
    { id: 'DBS Group', label: 'DBS Group', shape: 'box' },
    { id: 'SGX Ltd', label: 'SGX Ltd', shape: 'box' },
    { id: 'Sea Ltd', label: 'Sea Ltd', shape: 'box' },
    { id: 'OCBC Ltd', label: 'OCBC Ltd', shape: 'box' },
    { id: 'Grab Holdings', label: 'Grab Holdings', shape: 'box' },
    { id: 'ST Engineering', label: 'ST Engineering', shape: 'box' },
    { id: 'UOL', label: 'UOL', shape: 'box' },
    { id: 'Seatrium', label: 'Seatrium', shape: 'box' },
    { id: 'Lee Theng Kiat', label: 'Lee Theng Kiat', shape: 'ellipse', hidden: true },
    { id: 'Yong Ying-I', label: 'Yong Ying-I', shape: 'ellipse', hidden: true },
    { id: 'Tan Tze Gay', label: 'Tan Tze Gay', shape: 'ellipse', hidden: true },
    { id: 'Wee Siew Kim', label: 'Wee Siew Kim', shape: 'ellipse', hidden: true },
    { id: 'Yong Hsin Yue', label: 'Yong Hsin Yue', shape: 'ellipse', hidden: true },
    { id: 'Gautam Banerjee', label: 'Gautam Banerjee', shape: 'ellipse', hidden: true },
    { id: 'Lim Swee Say', label: 'Lim Swee Say', shape: 'ellipse', hidden: true },
    { id: 'Yuen Kuan Moon', label: 'Yuen Kuan Moon', shape: 'ellipse', hidden: true },
    { id: 'John Arthur', label: 'John Arthur', shape: 'ellipse', hidden: true },
    { id: 'Gail Kelly', label: 'Gail Kelly', shape: 'ellipse', hidden: true },
    { id: 'Dinesh Khanna', label: 'Dinesh Khanna', shape: 'ellipse', hidden: true },
    { id: 'Rajeev Suri', label: 'Rajeev Suri', shape: 'ellipse', hidden: true },
    { id: 'Ee Lim Wee', label: 'Ee Lim Wee', shape: 'ellipse', hidden: true },
    { id: 'Wee Sin Liam', label: 'Wee Sin Liam', shape: 'ellipse', hidden: true },
    { id: 'Ee Chao Wee', label: 'Ee Chao Wee', shape: 'ellipse', hidden: true },
    { id: 'Cheng Soon Lau', label: 'Cheng Soon Lau', shape: 'ellipse', hidden: true },
    { id: 'Hon Thang Poon', label: 'Hon Thang Poon', shape: 'ellipse', hidden: true },
    { id: 'Hwee Cher Sim', label: 'Hwee Cher Sim', shape: 'ellipse', hidden: true },
    { id: 'Chin Yong Lee', label: 'Chin Yong Lee', shape: 'ellipse', hidden: true },
    { id: 'Wai Yip', label: 'Wai Yip', shape: 'ellipse', hidden: true },
    { id: 'Tang Wee Loke', label: 'Tang Wee Loke', shape: 'ellipse', hidden: true },
    { id: 'Kuah Boon Wee', label: 'Kuah Boon Wee', shape: 'ellipse', hidden: true },
    { id: 'Andrew Suckling', label: 'Andrew Suckling', shape: 'ellipse', hidden: true },
    { id: 'Michael Tay', label: 'Michael Tay', shape: 'ellipse', hidden: true },
    { id: 'Edmund Leong', label: 'Edmund Leong', shape: 'ellipse', hidden: true },
    { id: 'Jason Leow', label: 'Jason Leow', shape: 'ellipse', hidden: true },
    { id: 'Chan Lay Hoon', label: 'Chan Lay Hoon', shape: 'ellipse', hidden: true },
    { id: 'Henry Hui', label: 'Henry Hui', shape: 'ellipse', hidden: true },
    { id: 'Wong Kan Seng', label: 'Wong Kan Seng', shape: 'ellipse', hidden: true },
    { id: 'Wee Ee Cheong', label: 'Wee Ee Cheong', shape: 'ellipse', hidden: true },
    { id: 'Michael Lien', label: 'Michael Lien', shape: 'ellipse', hidden: true },
    { id: 'Steven Phan', label: 'Steven Phan', shape: 'ellipse', hidden: true },
    { id: 'Chia Tai Tee', label: 'Chia Tai Tee', shape: 'ellipse', hidden: true },
    { id: 'Dinh Ba Thanh', label: 'Dinh Ba Thanh', shape: 'ellipse', hidden: true },
    { id: 'Teo Lay Lim', label: 'Teo Lay Lim', shape: 'ellipse', hidden: true },
    { id: 'Ong Chong Tee', label: 'Ong Chong Tee', shape: 'ellipse', hidden: true },
    { id: 'Lai Chung Han', label: 'Lai Chung Han', shape: 'ellipse', hidden: true },
    { id: 'Ow Fook Chuen', label: 'Ow Fook Chuen', shape: 'ellipse', hidden: true },
    { id: 'Fazli Mansor', label: 'Fazli Mansor', shape: 'ellipse', hidden: true },
    { id: 'Blossom Shan', label: 'Blossom Shan', shape: 'ellipse', hidden: true },
    { id: 'Lee Yan Hong', label: 'Lee Yan Hong', shape: 'ellipse', hidden: true },
    { id: 'Puah Kok Keong', label: 'Puah Kok Keong', shape: 'ellipse', hidden: true },
    { id: 'Lawrence Goh', label: 'Lawrence Goh', shape: 'ellipse', hidden: true },
    { id: 'Lee Chee Koon', label: 'Lee Chee Koon', shape: 'ellipse', hidden: true },
    { id: 'Vincent Chong', label: 'Vincent Chong', shape: 'ellipse', hidden: true },
    { id: 'Woo Li Fern', label: 'Woo Li Fern', shape: 'ellipse', hidden: true },
    { id: 'Ow Foong Pheng', label: 'Ow Foong Pheng', shape: 'ellipse', hidden: true },
    { id: 'Abdul Rahman', label: 'Abdul Rahman', shape: 'ellipse', hidden: true },
    { id: 'Chong Yoke Sin', label: 'Chong Yoke Sin', shape: 'ellipse', hidden: true },
    { id: 'Choo Oi Yee', label: 'Choo Oi Yee', shape: 'ellipse', hidden: true },
    { id: 'Goh Thien Phong', label: 'Goh Thien Phong', shape: 'ellipse', hidden: true },
    { id: 'Loh Chin Hua', label: 'Loh Chin Hua', shape: 'ellipse', hidden: true },
    { id: 'Thang Leng Leng', label: 'Thang Leng Leng', shape: 'ellipse', hidden: true },
    { id: 'Nina Yang', label: 'Nina Yang', shape: 'ellipse', hidden: true },
    { id: 'Janet Young', label: 'Janet Young', shape: 'ellipse', hidden: true },
    { id: 'Lim Eng Hwee', label: 'Lim Eng Hwee', shape: 'ellipse', hidden: true },
    { id: 'Jacqueline Poh', label: 'Jacqueline Poh', shape: 'ellipse', hidden: true },
    { id: 'Terence Seow', label: 'Terence Seow', shape: 'ellipse', hidden: true },
    { id: 'Muthukrishnan Ramaswami', label: 'Muthukrishnan Ramaswami', shape: 'ellipse', hidden: true },
    { id: 'Jamie Ang', label: 'Jamie Ang', shape: 'ellipse', hidden: true },
    { id: 'Marina Chin', label: 'Marina Chin', shape: 'ellipse', hidden: true },
    { id: 'Suree Rohan', label: 'Suree Rohan', shape: 'ellipse', hidden: true },
    { id: 'Roger Tan', label: 'Roger Tan', shape: 'ellipse', hidden: true },
    { id: 'David Tan', label: 'David Tan', shape: 'ellipse', hidden: true },
    { id: 'Kai Nargolwala', label: 'Kai Nargolwala', shape: 'ellipse', hidden: true },
    { id: 'Chong Lee Tan', label: 'Chong Lee Tan', shape: 'ellipse', hidden: true },
    { id: 'Kok Song Ng', label: 'Kok Song Ng', shape: 'ellipse', hidden: true },
    { id: 'Eugene Lai', label: 'Eugene Lai', shape: 'ellipse', hidden: true },
    { id: 'Chaly Mah Chee Kheong', label: 'Chaly Mah Chee Kheong', shape: 'ellipse', hidden: true },
    { id: 'Miguel Ko', label: 'Miguel Ko', shape: 'ellipse', hidden: true },
    { id: 'Judy Hsu', label: 'Judy Hsu', shape: 'ellipse', hidden: true },
    { id: 'David Su Tuong', label: 'David Su Tuong', shape: 'ellipse', hidden: true },
    { id: 'Tan Sri Abdul Farid Alias', label: 'Tan Sri Abdul Farid Alias', shape: 'ellipse', hidden: true },
    { id: 'Belita Ong', label: 'Belita Ong', shape: 'ellipse', hidden: true },
    { id: 'Tham Kui Seng', label: 'Tham Kui Seng', shape: 'ellipse', hidden: true },
    { id: 'Philip Lee', label: 'Philip Lee', shape: 'ellipse', hidden: true },
    { id: 'Jill Lee', label: 'Jill Lee', shape: 'ellipse', hidden: true },
    { id: 'Andrew Lim', label: 'Andrew Lim', shape: 'ellipse', hidden: true },
    { id: 'Chee Yen Gan', label: 'Chee Yen Gan', shape: 'ellipse', hidden: true },
    { id: 'Chew Gek Khim', label: 'Chew Gek Khim', shape: 'ellipse', hidden: true },
    { id: 'Chew Gek Hiang', label: 'Chew Gek Hiang', shape: 'ellipse', hidden: true },
    { id: 'Yong David', label: 'Yong David', shape: 'ellipse', hidden: true },
    { id: 'Chian Khong', label: 'Chian Khong', shape: 'ellipse', hidden: true },
    { id: 'Chua Tian Chu', label: 'Chua Tian Chu', shape: 'ellipse', hidden: true },
    { id: 'Lee Chuan Seng', label: 'Lee Chuan Seng', shape: 'ellipse', hidden: true },
    { id: 'Ho Tian Yee', label: 'Ho Tian Yee', shape: 'ellipse', hidden: true },
    { id: 'Lin Diaan Yi', label: 'Lin Diaan Yi', shape: 'ellipse', hidden: true },
    { id: 'Eu Zai Jonathon', label: 'Eu Zai Jonathon', shape: 'ellipse', hidden: true },
    { id: 'Yu Gokongwei', label: 'Yu Gokongwei', shape: 'ellipse', hidden: true },
    { id: 'Chng Hwee Hong', label: 'Chng Hwee Hong', shape: 'ellipse', hidden: true },
    { id: 'Tan Kiaw Ngoh', label: 'Tan Kiaw Ngoh', shape: 'ellipse', hidden: true },
    { id: 'Peter Sim', label: 'Peter Sim', shape: 'ellipse', hidden: true },
    { id: 'Ng Shin Ein', label: 'Ng Shin Ein', shape: 'ellipse', hidden: true },
    { id: 'Dara Khosrowshahi', label: 'Dara Khosrowshahi', shape: 'ellipse', hidden: true },
    { id: 'John Rogers', label: 'John Rogers', shape: 'ellipse', hidden: true },
    { id: 'Daniel Yun', label: 'Daniel Yun', shape: 'ellipse', hidden: true },
    { id: 'Steven Tishman', label: 'Steven Tishman', shape: 'ellipse', hidden: true },
    { id: 'Peter Oey', label: 'Peter Oey', shape: 'ellipse', hidden: true },
    { id: 'Cheryl Goh', label: 'Cheryl Goh', shape: 'ellipse', hidden: true },
    { id: 'Tan Tiong Cheng', label: 'Tan Tiong Cheng', shape: 'ellipse', hidden: true },
    { id: 'Yap Chee Keong', label: 'Yap Chee Keong', shape: 'ellipse', hidden: true },
    { id: 'Chris Ong', label: 'Chris Ong', shape: 'ellipse', hidden: true },
    { id: 'Sarjit Singh', label: 'Sarjit Singh', shape: 'ellipse', hidden: true },
    { id: 'Eng Aik Meng', label: 'Eng Aik Meng', shape: 'ellipse', hidden: true },
    { id: 'Mark Gainborough', label: 'Mark Gainborough', shape: 'ellipse', hidden: true },
    { id: 'Jan Holm', label: 'Jan Holm', shape: 'ellipse', hidden: true },
    { id: 'Ieda Gomes', label: 'Ieda Gomes', shape: 'ellipse', hidden: true },
    { id: 'Astrid Onsum', label: 'Astrid Onsum', shape: 'ellipse', hidden: true },
    { id: 'Mariel Schumann', label: 'Mariel Schumann', shape: 'ellipse', hidden: true },
    { id: 'Lee Jee Jenny', label: 'Lee Jee Jenny', shape: 'ellipse', hidden: true },
    { id: 'Chew Choon Soo', label: 'Chew Choon Soo', shape: 'ellipse', hidden: true },
    { id: 'Low Weng Keong', label: 'Low Weng Keong', shape: 'ellipse', hidden: true },
    { id: 'Ong Sim Ho', label: 'Ong Sim Ho', shape: 'ellipse', hidden: true },
    { id: 'Tan Kin Fei', label: 'Tan Kin Fei', shape: 'ellipse', hidden: true },
    { id: 'Chua Bin Hwee', label: 'Chua Bin Hwee', shape: 'ellipse', hidden: true },
    { id: 'Lim Kong Puay', label: 'Lim Kong Puay', shape: 'ellipse', hidden: true },
    { id: 'Chong Chuan Neo', label: 'Chong Chuan Neo', shape: 'ellipse', hidden: true },
    { id: 'Andrew Lee', label: 'Andrew Lee', shape: 'ellipse', hidden: true },
    { id: 'Chua Kim Chiu', label: 'Chua Kim Chiu', shape: 'ellipse', hidden: true },
    { id: 'Andrew Khoo', label: 'Andrew Khoo', shape: 'ellipse', hidden: true },
    { id: 'Lee Tih Shih', label: 'Lee Tih Shih', shape: 'ellipse', hidden: true },
    { id: 'Lian Wee Cheow', label: 'Lian Wee Cheow', shape: 'ellipse', hidden: true },
    { id: 'Pramukti Surjaudaja', label: 'Pramukti Surjaudaja', shape: 'ellipse', hidden: true },
    { id: 'Tan Kai Ping', label: 'Tan Kai Ping', shape: 'ellipse', hidden: true },
    { id: 'Ng Chee Khern', label: 'Ng Chee Khern', shape: 'ellipse', hidden: true },
    { id: 'Chin Yau Seng', label: 'Chin Yau Seng', shape: 'ellipse', hidden: true },
    { id: 'Melvyn Ong', label: 'Melvyn Ong', shape: 'ellipse', hidden: true },
    { id: 'Neo Gim Huay', label: 'Neo Gim Huay', shape: 'ellipse', hidden: true },
    { id: 'Ng Bee Bee', label: 'Ng Bee Bee', shape: 'ellipse', hidden: true },
    { id: 'Song Su-Min', label: 'Song Su-Min', shape: 'ellipse', hidden: true },
    { id: 'Tan Peng Yam', label: 'Tan Peng Yam', shape: 'ellipse', hidden: true },
    { id: 'Chong Shi Hao', label: 'Chong Shi Hao', shape: 'ellipse', hidden: true },
    { id: 'Lien Siaou-Sze', label: 'Lien Siaou-Sze', shape: 'ellipse', hidden: true },
    { id: 'Kevin Kwok', label: 'Kevin Kwok', shape: 'ellipse', hidden: true },
    { id: 'Ng Chad Son', label: 'Ng Chad Son', shape: 'ellipse', hidden: true },
    { id: 'Aaron Beng', label: 'Aaron Beng', shape: 'ellipse', hidden: true },
    { id: 'Cindy Khoo', label: 'Cindy Khoo', shape: 'ellipse', hidden: true },
    { id: 'Marcus Lam', label: 'Marcus Lam', shape: 'ellipse', hidden: true },
    { id: 'Tulika Mitra', label: 'Tulika Mitra', shape: 'ellipse', hidden: true },
    { id: 'Elaine Ng', label: 'Elaine Ng', shape: 'ellipse', hidden: true },
    { id: 'Siraj Omar', label: 'Siraj Omar', shape: 'ellipse', hidden: true },
    { id: 'Shamir Rahim', label: 'Shamir Rahim', shape: 'ellipse', hidden: true },
    { id: 'Tan Kok Yam', label: 'Tan Kok Yam', shape: 'ellipse', hidden: true },
    { id: 'Yew Chee Leung', label: 'Yew Chee Leung', shape: 'ellipse', hidden: true },
    { id: 'Temasek', label: 'Temasek', shape: 'box', hidden: true },
    { id: 'CPF', label: 'CPF', shape: 'box', hidden: true },
    { id: 'Ministry of Dig Dev & Info', label: 'Ministry of Dig Dev & Info', shape: 'box', hidden: true },
    { id: 'NUHS', label: 'NUHS', shape: 'box', hidden: true },
    { id: 'SIA Eng', label: 'SIA Eng', shape: 'box', hidden: true },
    { id: 'Jurong Port', label: 'Jurong Port', shape: 'box', hidden: true },
    { id: 'Nippon Paint', label: 'Nippon Paint', shape: 'box', hidden: true },
    { id: 'Kuok Group', label: 'Kuok Group', shape: 'box', hidden: true },
    { id: '65 equity partners', label: '65 equity partners', shape: 'box', hidden: true },
    { id: 'SIA', label: 'SIA', shape: 'box', hidden: true },
    { id: 'GIC', label: 'GIC', shape: 'box', hidden: true },
    { id: 'NTUC LearningHub', label: 'NTUC LearningHub', shape: 'box', hidden: true },
    { id: 'SIM', label: 'SIM', shape: 'box', hidden: true },
    { id: 'Euleen Goh', label: 'Euleen Goh', shape: 'ellipse', hidden: true },
    { id: 'Abel Ang', label: 'Abel Ang', shape: 'ellipse', hidden: true },
    { id: 'Chia Wee Boon', label: 'Chia Wee Boon', shape: 'ellipse', hidden: true },
    { id: 'David Chua', label: 'David Chua', shape: 'ellipse', hidden: true },
    { id: 'Vivian Chua', label: 'Vivian Chua', shape: 'ellipse', hidden: true },
    { id: 'Tinku Gupta', label: 'Tinku Gupta', shape: 'ellipse', hidden: true },
    { id: 'Nazri Othman', label: 'Nazri Othman', shape: 'ellipse', hidden: true },
    { id: 'Ooi Huey Tyng', label: 'Ooi Huey Tyng', shape: 'ellipse', hidden: true },
    { id: 'Sanjoy Sen', label: 'Sanjoy Sen', shape: 'ellipse', hidden: true },
    { id: 'Ng Pak Shun', label: 'Ng Pak Shun', shape: 'ellipse', hidden: true },
    { id: 'Malini Vaidya', label: 'Malini Vaidya', shape: 'ellipse', hidden: true },
    { id: 'Dawn Teo', label: 'Dawn Teo', shape: 'ellipse', hidden: true },
    { id: 'Wei Kwok Kee', label: 'Wei Kwok Kee', shape: 'ellipse', hidden: true },
    { id: 'DSTA', label: 'DSTA', shape: 'box', hidden: true },
    { id: 'Pan Pacific Hotels', label: 'Pan Pacific Hotels', shape: 'box', hidden: true },
    { id: 'Parkroyal Hotels', label: 'Parkroyal Hotels', shape: 'box', hidden: true },
    { id: 'Far East Hospitality', label: 'Far East Hospitality', shape: 'box', hidden: true },
    { id: 'United Industrial Corp', label: 'United Industrial Corp', shape: 'box', hidden: true },
    { id: 'Singapore Land Group', label: 'Singapore Land Group', shape: 'box', hidden: true },
    { id: 'UOB Ltd', label: 'UOB Ltd', shape: 'box', hidden: true },
    { id: 'Haw Par Corp Ltd', label: 'Haw Par Corp Ltd', shape: 'box', hidden: true },
    { id: 'UOB-Kay Hian', label: 'UOB-Kay Hian', shape: 'box', hidden: true },
    { id: 'The Straits Trading Company', label: 'The Straits Trading Company', shape: 'box', hidden: true },
    { id: 'Shangri-La Asia', label: 'Shangri-La Asia', shape: 'box', hidden: true },
    { id: 'Sembcorp Industries', label: 'Sembcorp Industries', shape: 'box', hidden: true },
    { id: 'Ensign Infosecurity', label: 'Ensign Infosecurity', shape: 'box', hidden: true },
    { id: 'Singlife Holdings', label: 'Singlife Holdings', shape: 'box', hidden: true },
    { id: 'Olam Group', label: 'Olam Group', shape: 'box', hidden: true },
    { id: 'Maritime Port Authority Singapore', label: 'Maritime Port Authority Singapore', shape: 'box', hidden: true },
    { id: 'IRA Singapore', label: 'IRA Singapore', shape: 'box', hidden: true },
    { id: 'URA Singapore', label: 'URA Singapore', shape: 'box', hidden: true },
    { id: 'SATS Ltd', label: 'SATS Ltd', shape: 'box', hidden: true },
    { id: 'Sembcorp Marine', label: 'Sembcorp Marine', shape: 'box', hidden: true },
    { id: 'Keppel Offshore', label: 'Keppel Offshore', shape: 'box', hidden: true },
    { id: 'Keppel Corp', label: 'Keppel Corp', shape: 'box', hidden: true },
    { id: 'JTC Corp', label: 'JTC Corp', shape: 'box', hidden: true },
    { id: 'Shell', label: 'Shell', shape: 'box', hidden: true },
    { id: 'ExxonMobil', label: 'ExxonMobil', shape: 'box', hidden: true },
    { id: 'BP', label: 'BP', shape: 'box', hidden: true },
    { id: 'Equinor', label: 'Equinor', shape: 'box', hidden: true },
    { id: 'TotalEnergies', label: 'TotalEnergies', shape: 'box', hidden: true },
    { id: 'Chevron', label: 'Chevron', shape: 'box', hidden: true },
    { id: 'Lim Boon Heng', label: 'Lim Boon Heng', shape: 'ellipse', hidden: true },
    { id: 'Teo Chee Hean', label: 'Teo Chee Hean', shape: 'ellipse', hidden: true },
    { id: 'Jenny Lee', label: 'Jenny Lee', shape: 'ellipse', hidden: true },
    { id: 'Ong Pang Thye', label: 'Ong Pang Thye', shape: 'ellipse', hidden: true },
    { id: 'Jim Hagemann', label: 'Jim Hagemann', shape: 'ellipse', hidden: true },
    { id: 'Tan Chee Meng', label: 'Tan Chee Meng', shape: 'ellipse', hidden: true },
    { id: 'Tan Chong Meng', label: 'Tan Chong Meng', shape: 'ellipse', hidden: true },
    { id: 'Peter Voser', label: 'Peter Voser', shape: 'ellipse', hidden: true },
    { id: 'Geoffrey Wong', label: 'Geoffrey Wong', shape: 'ellipse', hidden: true },
    { id: 'Jaime Augusto', label: 'Jaime Augusto', shape: 'ellipse', hidden: true },
    { id: 'Dilhan Pillay', label: 'Dilhan Pillay', shape: 'ellipse', hidden: true },
    { id: 'Gan Kim Yong (DPM)', label: 'Gan Kim Yong (DPM)', shape: 'ellipse', hidden: true },
    { id: 'Heng Swee Keat (Chairman)', label: 'Heng Swee Keat (Chairman)', shape: 'ellipse', hidden: true },
    { id: 'Lim Hng Kiang', label: 'Lim Hng Kiang', shape: 'ellipse', hidden: true },
    { id: 'Ang Kong Hua', label: 'Ang Kong Hua', shape: 'ellipse', hidden: true },
    { id: 'Hsieh Fu Hua', label: 'Hsieh Fu Hua', shape: 'ellipse', hidden: true },
    { id: 'Loh Boon Chye', label: 'Loh Boon Chye', shape: 'ellipse', hidden: true },
    { id: 'Koh Boon Hwee', label: 'Koh Boon Hwee', shape: 'ellipse', hidden: true },
    { id: 'Seck Wai Kwong', label: 'Seck Wai Kwong', shape: 'ellipse', hidden: true },
    { id: 'Lim Chow Kiat (CEO)', label: 'Lim Chow Kiat (CEO)', shape: 'ellipse', hidden: true },
    { id: 'Bryan Yeo (CIO)', label: 'Bryan Yeo (CIO)', shape: 'ellipse', hidden: true },
    { id: 'Eugene Wong', label: 'Eugene Wong', shape: 'ellipse', hidden: true },
    { id: 'Desmond Tan', label: 'Desmond Tan', shape: 'ellipse', hidden: true },
    { id: 'Joyce Lee', label: 'Joyce Lee', shape: 'ellipse', hidden: true },
    { id: 'Don Yeo', label: 'Don Yeo', shape: 'ellipse', hidden: true },
    { id: 'Yeo Li Pheow', label: 'Yeo Li Pheow', shape: 'ellipse', hidden: true },
    { id: 'Andy Lim', label: 'Andy Lim', shape: 'ellipse', hidden: true },
    { id: 'Jennie Chua (Chairman)', label: 'Jennie Chua (Chairman)', shape: 'ellipse', hidden: true },
    { id: 'Zuraidah Abdullah', label: 'Zuraidah Abdullah', shape: 'ellipse', hidden: true },
    { id: 'Goh Geok Khim', label: 'Goh Geok Khim', shape: 'ellipse', hidden: true },
    { id: 'Koo Tsai Kee', label: 'Koo Tsai Kee', shape: 'ellipse', hidden: true },
    { id: 'Benny Lim', label: 'Benny Lim', shape: 'ellipse', hidden: true },
    { id: 'Quek See Tiat', label: 'Quek See Tiat', shape: 'ellipse', hidden: true },
    { id: 'Arif Rachmat', label: 'Arif Rachmat', shape: 'ellipse', hidden: true },
    { id: 'Prof Leo Tan', label: 'Prof Leo Tan', shape: 'ellipse', hidden: true },
    { id: 'Tan Soo Nan', label: 'Tan Soo Nan', shape: 'ellipse', hidden: true },
    { id: 'Teo Ming Kian', label: 'Teo Ming Kian', shape: 'ellipse', hidden: true },
    { id: 'Ng Boon Heong', label: 'Ng Boon Heong', shape: 'ellipse', hidden: true },
    { id: 'Yeoh Khay Guan', label: 'Yeoh Khay Guan', shape: 'ellipse', hidden: true },
    { id: 'Kenneth Mak', label: 'Kenneth Mak', shape: 'ellipse', hidden: true },
    { id: 'Tan Eng Chye', label: 'Tan Eng Chye', shape: 'ellipse', hidden: true },
    { id: 'Vincent Chin', label: 'Vincent Chin', shape: 'ellipse', hidden: true },
    { id: 'Mildred Tan', label: 'Mildred Tan', shape: 'ellipse', hidden: true },
    { id: 'Lim Yean Teng', label: 'Lim Yean Teng', shape: 'ellipse', hidden: true },
    { id: 'Tracey Woon', label: 'Tracey Woon', shape: 'ellipse', hidden: true },
    { id: 'Ishak Ismail', label: 'Ishak Ismail', shape: 'ellipse', hidden: true },
    { id: 'Cham Hui Fong', label: 'Cham Hui Fong', shape: 'ellipse', hidden: true },
    { id: 'Deanna Ong', label: 'Deanna Ong', shape: 'ellipse', hidden: true },
    { id: 'Wong Heang Fine', label: 'Wong Heang Fine', shape: 'ellipse', hidden: true },
    { id: 'James Donovan', label: 'James Donovan', shape: 'ellipse', hidden: true },
    { id: 'Yeoh KC', label: 'Yeoh KC', shape: 'ellipse', hidden: true },
    { id: 'Melissa Khoo (CEO)', label: 'Melissa Khoo (CEO)', shape: 'ellipse', hidden: true },
    { id: 'Kenny Tan', label: 'Kenny Tan', shape: 'ellipse', hidden: true },
    { id: 'Titus Lee', label: 'Titus Lee', shape: 'ellipse', hidden: true },
    { id: 'Tan Hee Teck', label: 'Tan Hee Teck', shape: 'ellipse', hidden: true },
    { id: 'Kohe Hasan', label: 'Kohe Hasan', shape: 'ellipse', hidden: true },
    { id: 'K Thanaletchimi', label: 'K Thanaletchimi', shape: 'ellipse', hidden: true },
    { id: 'Caryn Lim', label: 'Caryn Lim', shape: 'ellipse', hidden: true },
    { id: 'Lai Wei Lin', label: 'Lai Wei Lin', shape: 'ellipse', hidden: true },
    { id: 'Liew Tzu Mi', label: 'Liew Tzu Mi', shape: 'ellipse', hidden: true },
    { id: 'Anthony Lim', label: 'Anthony Lim', shape: 'ellipse', hidden: true },
    { id: 'Marcus Lim', label: 'Marcus Lim', shape: 'ellipse', hidden: true },
    { id: 'Jessica Tan', label: 'Jessica Tan', shape: 'ellipse', hidden: true },
    { id: 'forrest Li', label: 'forrest Li', shape: 'ellipse', hidden: true },
    { id: 'Gang Ye', label: 'Gang Ye', shape: 'ellipse', hidden: true },
    { id: 'David Ma', label: 'David Ma', shape: 'ellipse', hidden: true },
    { id: 'David Heng', label: 'David Heng', shape: 'ellipse', hidden: true },
    { id: 'Khoon Hua kuok', label: 'Khoon Hua kuok', shape: 'ellipse', hidden: true },
    { id: 'Silvio Savarese', label: 'Silvio Savarese', shape: 'ellipse', hidden: true },
    { id: 'Rowena Yeo', label: 'Rowena Yeo', shape: 'ellipse', hidden: true },
    { id: 'Sunny Verghese', label: 'Sunny Verghese', shape: 'ellipse', hidden: true },
    { id: 'Peter Bakker', label: 'Peter Bakker', shape: 'ellipse', hidden: true },
    { id: 'Steve Howard', label: 'Steve Howard', shape: 'ellipse', hidden: true },
    { id: 'Ruth Nussbaum', label: 'Ruth Nussbaum', shape: 'ellipse', hidden: true },
    { id: 'Alan Thompson', label: 'Alan Thompson', shape: 'ellipse', hidden: true },
    { id: 'NTUC Enterprise Coop', label: 'NTUC Enterprise Coop', shape: 'box', hidden: true },
    { id: 'NTUC Health for Life', label: 'NTUC Health for Life', shape: 'box', hidden: true },
    { id: 'Philanthropy Asia Limited', label: 'Philanthropy Asia Limited', shape: 'box', hidden: true },
    { id: 'Duke NUS Medical School', label: 'Duke NUS Medical School', shape: 'box', hidden: true },
    { id: 'LKY School of Public Policy', label: 'LKY School of Public Policy', shape: 'box', hidden: true },
    { id: 'SP Group', label: 'SP Group', shape: 'box', hidden: true },
    { id: 'MOH Holdings', label: 'MOH Holdings', shape: 'box', hidden: true },
    { id: 'PSA', label: 'PSA', shape: 'box', hidden: true },
    { id: 'ABB Ltd', label: 'ABB Ltd', shape: 'box', hidden: true },
    { id: 'IBM Corp', label: 'IBM Corp', shape: 'box', hidden: true },
    { id: 'Seviora Holdings', label: 'Seviora Holdings', shape: 'box', hidden: true },
    { id: 'Enterprise Singapore', label: 'Enterprise Singapore', shape: 'box', hidden: true },
    { id: 'Temasek Foundation', label: 'Temasek Foundation', shape: 'box', hidden: true },
    { id: 'SkillsFuture Singapore', label: 'SkillsFuture Singapore', shape: 'box', hidden: true },
    { id: 'Tan Kai Hoe', label: 'Tan Kai Hoe', shape: 'ellipse', hidden: true },
    { id: 'Abdul Samad Bin Abdul Wahab', label: 'Abdul Samad Bin Abdul Wahab', shape: 'ellipse', hidden: true },
    { id: 'Adeline Sim', label: 'Adeline Sim', shape: 'ellipse', hidden: true },
    { id: 'Albert Pek', label: 'Albert Pek', shape: 'ellipse', hidden: true },
    { id: 'Ang Zhongren', label: 'Ang Zhongren', shape: 'ellipse', hidden: true },
    { id: 'Chang Sau Sheong', label: 'Chang Sau Sheong', shape: 'ellipse', hidden: true },
    { id: 'Deborah Ong', label: 'Deborah Ong', shape: 'ellipse', hidden: true },
    { id: 'Dilys Boey', label: 'Dilys Boey', shape: 'ellipse', hidden: true },
    { id: 'Eleanor Seet', label: 'Eleanor Seet', shape: 'ellipse', hidden: true },
    { id: 'Feon Ang', label: 'Feon Ang', shape: 'ellipse', hidden: true },
    { id: 'Susan Chong', label: 'Susan Chong', shape: 'ellipse', hidden: true },
    { id: 'GenZero', label: 'GenZero', shape: 'box', hidden: true },


    // Duke-NUS Medical School: person nodes added (hidden by default)
    { id: 'Goh Yew Lin', label: 'Goh Yew Lin', shape: 'ellipse', hidden: true },
    { id: 'Aaron Thean', label: 'Aaron Thean', shape: 'ellipse', hidden: true },
    { id: 'Fidah Alsagoff', label: 'Fidah Alsagoff', shape: 'ellipse', hidden: true },
    { id: 'Edward G. Buckley', label: 'Edward G. Buckley', shape: 'ellipse', hidden: true },
    { id: 'Chng Hak-Peng', label: 'Chng Hak-Peng', shape: 'ellipse', hidden: true },
    { id: 'Karen Chong', label: 'Karen Chong', shape: 'ellipse', hidden: true },
    { id: 'Stacy Choong Hui Hui', label: 'Stacy Choong Hui Hui', shape: 'ellipse', hidden: true },
    { id: 'Mary E Klotman', label: 'Mary E Klotman', shape: 'ellipse', hidden: true },
    // Lee Hong Wei Jenny removed per request
    { id: 'Lee Sze Yeng', label: 'Lee Sze Yeng', shape: 'ellipse', hidden: true },
    { id: 'Mak Lye Mun', label: 'Mak Lye Mun', shape: 'ellipse', hidden: true },
    { id: 'Ivy Ng Swee Lian', label: 'Ivy Ng Swee Lian', shape: 'ellipse', hidden: true },
    { id: 'Ng Wai Hoe', label: 'Ng Wai Hoe', shape: 'ellipse', hidden: true },
    { id: 'Marie Elaine Teo', label: 'Marie Elaine Teo', shape: 'ellipse', hidden: true },
    { id: 'Kuok Khoon Ean', label: 'Kuok Khoon Ean', shape: 'ellipse', hidden: true },
    { id: 'Kay Kuok', label: 'Kay Kuok', shape: 'ellipse', hidden: true },
    { id: 'Kuok Khoon Hua', label: 'Kuok Khoon Hua', shape: 'ellipse', hidden: true },
    { id: 'Thai Kum Foon', label: 'Thai Kum Foon', shape: 'ellipse', hidden: true },
    { id: 'Low Soon Teck', label: 'Low Soon Teck', shape: 'ellipse', hidden: true },
    { id: 'Tho Leong Chye', label: 'Tho Leong Chye', shape: 'ellipse', hidden: true },
    { id: 'Kuok Meng Xiong', label: 'Kuok Meng Xiong', shape: 'ellipse', hidden: true },
    { id: 'Jeremy Goon', label: 'Jeremy Goon', shape: 'ellipse', hidden: true },
    { id: 'Lim Ah Doo', label: 'Lim Ah Doo', shape: 'ellipse', hidden: true },
    { id: 'Tran Phuoc', label: 'Tran Phuoc', shape: 'ellipse', hidden: true },
    { id: 'Ajai Puri', label: 'Ajai Puri', shape: 'ellipse', hidden: true },
    { id: 'Joerg Wolle', label: 'Joerg Wolle', shape: 'ellipse', hidden: true },
    { id: 'Nagi Hamiyeh', label: 'Nagi Hamiyeh', shape: 'ellipse', hidden: true },
    { id: 'Shuji Kobayashi', label: 'Shuji Kobayashi', shape: 'ellipse', hidden: true },
    { id: 'Yasuaki Matsuo', label: 'Yasuaki Matsuo', shape: 'ellipse', hidden: true },
    { id: 'Irving Tan', label: 'Irving Tan', shape: 'ellipse', hidden: true },
    { id: 'Kerry Mok', label: 'Kerry Mok', shape: 'ellipse', hidden: true },
    { id: 'Vinita Bali', label: 'Vinita Bali', shape: 'ellipse', hidden: true },
    { id: 'Chan Lai Fung', label: 'Chan Lai Fung', shape: 'ellipse', hidden: true },
    { id: 'Mak Swee Wah', label: 'Mak Swee Wah', shape: 'ellipse', hidden: true },
    { id: 'Pier Luigi Sigismondi', label: 'Pier Luigi Sigismondi', shape: 'ellipse', hidden: true },
    { id: 'Charles Ng', label: 'Charles Ng', shape: 'ellipse', hidden: true },
    { id: 'Paul Tan', label: 'Paul Tan', shape: 'ellipse', hidden: true },
    { id: 'Zong Fu Chua', label: 'Zong Fu Chua', shape: 'ellipse', hidden: true },
    { id: 'Ah Tuan Tan', label: 'Ah Tuan Tan', shape: 'ellipse', hidden: true },
    { id: 'Minhan Lim', label: 'Minhan Lim', shape: 'ellipse', hidden: true },
    { id: 'Kok Leong Chan', label: 'Kok Leong Chan', shape: 'ellipse', hidden: true },
    { id: 'Steven Ng', label: 'Steven Ng', shape: 'ellipse', hidden: true },
    { id: 'Diana Tan', label: 'Diana Tan', shape: 'ellipse', hidden: true },
    { id: 'Lee Chuan Teck', label: 'Lee Chuan Teck', shape: 'ellipse', hidden: true },
    { id: 'Ameera Ashraf', label: 'Ameera Ashraf', shape: 'ellipse', hidden: true },
    { id: 'Khoo Boo Hor', label: 'Khoo Boo Hor', shape: 'ellipse', hidden: true },
    { id: 'Peter Lam', label: 'Peter Lam', shape: 'ellipse', hidden: true },
    { id: 'Cindy Lim', label: 'Cindy Lim', shape: 'ellipse', hidden: true },
    { id: 'Lim Ming Yan', label: 'Lim Ming Yan', shape: 'ellipse', hidden: true },
    { id: 'Michael Muller', label: 'Michael Muller', shape: 'ellipse', hidden: true },
    { id: 'Png Cheong Boon', label: 'Png Cheong Boon', shape: 'ellipse', hidden: true },
    { id: 'Png Chin Yee', label: 'Png Chin Yee', shape: 'ellipse', hidden: true },
    { id: 'Paul Santos', label: 'Paul Santos', shape: 'ellipse', hidden: true },
    { id: 'Sim Feng-Ji', label: 'Sim Feng-Ji', shape: 'ellipse', hidden: true },
    { id: 'Satveer Singh Thakral', label: 'Satveer Singh Thakral', shape: 'ellipse', hidden: true },
    { id: 'Helen Wong', label: 'Helen Wong', shape: 'ellipse', hidden: true },
    { id: 'Gabriel Lim', label: 'Gabriel Lim', shape: 'ellipse', hidden: true },
    { id: 'Jimmy Phoon', label: 'Jimmy Phoon', shape: 'ellipse', hidden: true },
    { id: 'Rohit Sipahimalani', label: 'Rohit Sipahimalani', shape: 'ellipse', hidden: true },
    { id: 'Vijay Chandur Advani', label: 'Vijay Chandur Advani', shape: 'ellipse', hidden: true },
    { id: 'Lucas Tran', label: 'Lucas Tran', shape: 'ellipse', hidden: true },
    { id: 'Timothy Dattels', label: 'Timothy Dattels', shape: 'ellipse', hidden: true },
    { id: 'Chan Wai Ching', label: 'Chan Wai Ching', shape: 'ellipse', hidden: true },
    { id: 'John Marren', label: 'John Marren', shape: 'ellipse', hidden: true },
    { id: 'Leong Wai Leng', label: 'Leong Wai Leng', shape: 'ellipse', hidden: true },
    { id: 'Timothy Chia Chee Ming', label: 'Timothy Chia Chee Ming', shape: 'ellipse', hidden: true },
    { id: 'Lee Kim Shin', label: 'Lee Kim Shin', shape: 'ellipse', hidden: true },
    { id: 'Goh Swee Chen', label: 'Goh Swee Chen', shape: 'ellipse', hidden: true },
    { id: 'Yaacob Bin Ibrahim', label: 'Yaacob Bin Ibrahim', shape: 'ellipse', hidden: true },
    { id: 'Antonio Volpin', label: 'Antonio Volpin', shape: 'ellipse', hidden: true },
    { id: 'Ching Wei Hong', label: 'Ching Wei Hong', shape: 'ellipse', hidden: true },
    { id: 'Stanley Huang Tian Guan', label: 'Stanley Huang Tian Guan', shape: 'ellipse', hidden: true },
    { id: 'Beh Swan Gin', label: 'Beh Swan Gin', shape: 'ellipse', hidden: true },
    { id: 'Chng Sok Hui', label: 'Chng Sok Hui', shape: 'ellipse', hidden: true },
    { id: 'Julie Gao', label: 'Julie Gao', shape: 'ellipse', hidden: true },
    { id: 'Datuk Maimoonah Hussain', label: 'Datuk Maimoonah Hussain', shape: 'ellipse', hidden: true },
    { id: 'Stuart Lewis', label: 'Stuart Lewis', shape: 'ellipse', hidden: true },
    { id: 'Lim Chin Hu', label: 'Lim Chin Hu', shape: 'ellipse', hidden: true },
    { id: 'Danny Teoh', label: 'Danny Teoh', shape: 'ellipse', hidden: true },
    { id: 'Piyush Gupta', label: 'Piyush Gupta', shape: 'ellipse', hidden: true },
    { id: 'Shirish Apte', label: 'Shirish Apte', shape: 'ellipse', hidden: true },
    { id: 'Olivier Blum', label: 'Olivier Blum', shape: 'ellipse', hidden: true },
    { id: 'Nee Koon Hean Chua Cheong', label: 'Nee Koon Hean Chua Cheong', shape: 'ellipse', hidden: true },
    { id: 'Kai Yuan Wong', label: 'Kai Yuan Wong', shape: 'ellipse', hidden: true },
    { id: 'Lim Huat Seah', label: 'Lim Huat Seah', shape: 'ellipse', hidden: true },
    { id: 'Sae Peng Cheong', label: 'Sae Peng Cheong', shape: 'ellipse', hidden: true },
    { id: 'Chiu Fai Ho', label: 'Chiu Fai Ho', shape: 'ellipse', hidden: true },
    { id: 'David Gledhill', label: 'David Gledhill', shape: 'ellipse', hidden: true },
    { id: 'Capitaland Investment', label: 'Capitaland Investment', shape: 'box', hidden: true },
];



const directorCompanies = {
    // Singtel Directors - already complete
    'Lee Theng Kiat': ['Singtel','Temasek'],
    'Yong Ying-I': ['Singtel','CPF','Ministry of Dig Dev & Info','NUHS'],
    'Tan Tze Gay': ['Singtel','SIA Eng'],
    'Wee Siew Kim': ['Singtel','Jurong Port','Nippon Paint','SIA Eng','JTC Corp'],
    'Yong Hsin Yue': ['Singtel','Kuok Group','65 equity partners'],
    'Gautam Banerjee': ['Singtel','SIA','GIC'],
    'Lim Swee Say': ['Singtel','NTUC LearningHub','Temasek Foundation'],
    'Yuen Kuan Moon': ['Singtel','SIM','DSTA'],
    'John Arthur': ['Singtel'],
    'Gail Kelly': ['Singtel'],
    'Rajeev Suri': ['Singtel'],

    // SIA Directors (updated board)
    'Peter Seah': ['SIA','GIC','DBS Group'],
    'Goh Choon Phong': ['SIA'],
    'Simon Cheong': ['SIA'],
    'David John': ['SIA'],
    'Dominic Ho': ['SIA'],
    'Jeanette Wong': ['SIA','GIC'],
    'Yeoh Oon Jin': ['SIA','SGX Ltd'],

    // UOL Directors - updated: removed UOB Ltd from Lee Chin Yong Francis
    'Ee Lim Wee': ['UOL','Singapore Land Group','UOB Ltd','Haw Par Corp Ltd'],
    'Wee Sin Liam': ['UOL','Singapore Land Group'],
    'Ee Chao Wee': ['UOL','UOB-Kay Hian','Haw Par Corp Ltd'],
    'Cheng Soon Lau': ['UOL','The Straits Trading Company'],
    'Hon Thang Poon': ['UOL','The Straits Trading Company'],
    'Hwee Cher Sim': ['UOL'],
    'Chin Yong Lee': ['UOL'],
    'Wai Yip': ['UOL'],

    // UOB‑Kay Hian Directors (new mapping entries)
    'Tang Wee Loke': ['UOB-Kay Hian'],
    'Kuah Boon Wee': ['UOB-Kay Hian'],
    'Andrew Suckling': ['UOB-Kay Hian'],
    'Michael Tay': ['UOB-Kay Hian'],
    'Edmund Leong': ['UOB-Kay Hian'],
    'Jason Leow': ['UOB-Kay Hian'],
    'Chan Lay Hoon': ['UOB-Kay Hian'],
    'Henry Hui': ['UOB-Kay Hian'],

    // UOB Ltd Directors (new mapping entries)
    'Wong Kan Seng': ['UOB Ltd'],
    'Wee Ee Cheong': ['UOB Ltd'],
    'Michael Lien': ['UOB Ltd'],
    'Steven Phan': ['UOB Ltd'],
    'Tracey Woon': ['UOB Ltd','NUHS'],
    'Dinh Ba Thanh': ['UOB Ltd'],
    'Teo Lay Lim': ['UOB Ltd'],
    'Ong Chong Tee': ['UOB Ltd'],

    // Seatrium Directors
    'Chris Ong': ['Seatrium','Maritime Port Authority Singapore'],
    'Sarjit Singh': ['Seatrium','URA Singapore','CPF'],
    'Mark Gainborough': ['Seatrium'],
    'Jan Holm': ['Seatrium'],
    'Ieda Gomes': ['Seatrium'],
    'Astrid Onsum': ['Seatrium'],
    'Mariel Schumann': ['Seatrium'],

    // SATS Ltd Directors
    'Irving Tan': ['SATS Ltd'],
    'Kerry Mok': ['SATS Ltd'],
    'Vinita Bali': ['SATS Ltd'],
    'Chan Lai Fung': ['SATS Ltd'],
    'Mak Swee Wah': ['SATS Ltd'],
    'Pier Luigi Sigismondi': ['SATS Ltd'],
    'Jessica Tan': ['CPF','SATS Ltd','Sea Ltd'],

    // IRA Singapore Directors
    'Lai Chung Han': ['IRA Singapore'],
    'Ow Fook Chuen': ['IRA Singapore'],
    'Chia Tai Tee': ['UOB Ltd','IRA Singapore'],
    'Fazli Mansor': ['IRA Singapore'],
    'Blossom Shan': ['IRA Singapore'],
    'Lee Yan Hong': ['IRA Singapore'],
    'Puah Kok Keong': ['IRA Singapore'],
    'Lawrence Goh': ['IRA Singapore'],
    'Lee Chee Koon': ['IRA Singapore','Capitaland Investment'],
    'Woo Li Fern': ['IRA Singapore'],

    // URA Singapore Directors
    'Abdul Rahman': ['URA Singapore'],
    'Chong Yoke Sin': ['URA Singapore'],
    'Choo Oi Yee': ['URA Singapore'],
    'Goh Thien Phong': ['URA Singapore'],
    'Loh Chin Hua': ['URA Singapore','Keppel Corp'],
    'Keith Tan': ['URA Singapore','JTC Corp'],
    'Thang Leng Leng': ['URA Singapore'],
    'Nina Yang': ['URA Singapore'],
    'Janet Young': ['URA Singapore'],
    'Lim Eng Hwee': ['URA Singapore'],

    // Jurong Port Directors
    'Jacqueline Poh': ['Jurong Port','JTC Corp'],
    'Terence Seow': ['Jurong Port'],
    'Muthukrishnan Ramaswami': ['Jurong Port','NUHS','JTC Corp'],
    'Vincent Chong': ['IRA Singapore','Jurong Port','ST Engineering'],
    'Jamie Ang': ['Jurong Port'],
    'Marina Chin': ['Jurong Port'],
    'Suree Rohan': ['Jurong Port'],
    'Roger Tan': ['Jurong Port'],
    'David Tan': ['Jurong Port'],

    // 65 Equity Partners Directors (updated board)
    'Kai Nargolwala': ['65 equity partners'],
    'Chong Lee Tan': ['65 equity partners'],
    'Eng Aik Meng': ['Seatrium','65 equity partners','SATS Ltd'],
    'Kok Song Ng': ['65 equity partners'],
    'Eugene Lai': ['65 equity partners','Capitaland Investment'],
    // Kuok Group directors
    'Kuok Khoon Ean': ['Kuok Group'],
    'Kay Kuok': ['Kuok Group'],
    'Kuok Khoon Hua': ['Kuok Group'],
    'Thai Kum Foon': ['Kuok Group'],
    'Low Soon Teck': ['Kuok Group'],
    'Tho Leong Chye': ['Kuok Group'],
    'Kuok Meng Xiong': ['Kuok Group'],
    'Jeremy Goon': ['Kuok Group'],
    'Philip Lee': ['65 equity partners','ST Engineering'],
    'Jill Lee': ['65 equity partners'],
    'Chee Yen Gan': ['65 equity partners'],

    // SkillsFuture Singapore
    'Tan Kai Hoe': ['SkillsFuture Singapore'],
    'Abdul Samad Bin Abdul Wahab': ['SkillsFuture Singapore'],
    'Adeline Sim': ['SkillsFuture Singapore'],
    'Albert Pek': ['SkillsFuture Singapore'],
    'Ang Zhongren': ['SkillsFuture Singapore'],
    'Chang Sau Sheong': ['SkillsFuture Singapore'],
    'Deborah Ong': ['SkillsFuture Singapore'],
    'Dilys Boey': ['SkillsFuture Singapore'],
    'Eleanor Seet': ['SkillsFuture Singapore'],
    'Feon Ang': ['SkillsFuture Singapore'],
    'Susan Chong': ['SkillsFuture Singapore'],

    // SIM board members
    'Euleen Goh': ['SIM'],
    'Abel Ang': ['SIM'],
    'Chia Wee Boon': ['SIM'],
    'David Chua': ['SIM'],
    'Vivian Chua': ['SIM'],
    'Tinku Gupta': ['SIM'],
    'Nazri Othman': ['SIM'],
    'Ooi Huey Tyng': ['SIM'],
    'Sanjoy Sen': ['SIM'],
    'Ng Pak Shun': ['SIM'],
    'Malini Vaidya': ['SIM'],
    'Dawn Teo': ['SIM'],
    'Wei Kwok Kee': ['SIM'],

    // The Straits Trading Company Directors
    'Chew Gek Khim': ['The Straits Trading Company'],
    'Chew Gek Hiang': ['The Straits Trading Company'],
    'Yong David': ['The Straits Trading Company'],
    'Chian Khong': ['The Straits Trading Company'],
    'Chua Tian Chu': ['The Straits Trading Company'],
    'Lee Chuan Seng': ['The Straits Trading Company'],
    'Ho Tian Yee': ['The Straits Trading Company'],
    'Lin Diaan Yi': ['The Straits Trading Company'],

    // Singapore Land Group Directors - already complete
    'Eu Zai Jonathon': ['Singapore Land Group'],
    'Yu Gokongwei': ['Singapore Land Group'],
    'Chng Hwee Hong': ['Singapore Land Group'],
    'Tan Kiaw Ngoh': ['Singapore Land Group'],
    'Peter Sim': ['Singapore Land Group'],
    'Ng Shin Ein': ['Singapore Land Group','Grab Holdings'],
    'Tan Tiong Cheng': ['Singapore Land Group'],

    // Haw Par Corp Directors - already complete
    'Lee Jee Jenny': ['Haw Par Corp Ltd'],
    'Chew Choon Soo': ['Haw Par Corp Ltd'],
    'Low Weng Keong': ['Haw Par Corp Ltd'],
    'Ong Sim Ho': ['Haw Par Corp Ltd'],

    // SIA Eng Directors - already complete
    'Tan Kin Fei': ['SIA Eng'],
    'Chua Bin Hwee': ['SIA Eng'],
    'Lim Kong Puay': ['SIA Eng'],
    'Chong Chuan Neo': ['SIA Eng','OCBC Ltd'],
    'Tan Kai Ping': ['SIA Eng'],
    'Ng Chee Khern': ['SIA Eng'],
    'Chin Yau Seng': ['SIA Eng'],

    // DSTA Directors - already complete
    'Melvyn Ong': ['DSTA','ST Engineering'],
    'Ng Chad Son': ['DSTA'],
    'Aaron Beng': ['DSTA','ST Engineering','JTC Corp'],
    'Marcus Lam': ['DSTA'],
    'Tulika Mitra': ['DSTA'],
    'Elaine Ng': ['DSTA'],
    'Siraj Omar': ['DSTA'],
    'Shamir Rahim': ['DSTA'],
    'Tan Kok Yam': ['DSTA'],
    'Teo Ming Kian': ['Temasek Foundation','DSTA','ST Engineering'],
    'Yew Chee Leung': ['DSTA'],

    // GIC Directors
    'Gan Kim Yong (DPM)': ['GIC'],
    'Heng Swee Keat (Chairman)': ['GIC'],
    'Lim Hng Kiang': ['GIC'],
    'Ang Kong Hua': ['GIC'],
    'Hsieh Fu Hua': ['GIC'],
    'Loh Boon Chye': ['GIC','SGX Ltd'],
    'Koh Boon Hwee': ['GIC','SGX Ltd'],
    'Seck Wai Kwong': ['GIC','OCBC Ltd'],
    'Lim Chow Kiat (CEO)': ['GIC'],
    'Bryan Yeo (CIO)': ['GIC'],

    // NTUC LearningHub Directors
    'Eugene Wong': ['NTUC LearningHub'],
    'Desmond Tan': ['NTUC LearningHub'],
    'Joyce Lee': ['NTUC LearningHub'],
    'Don Yeo': ['NTUC LearningHub'],
    'Yeo Li Pheow': ['NTUC LearningHub'],
    'Andy Lim': ['NTUC LearningHub'],

    // Temasek Foundation Directors
    'Jennie Chua (Chairman)': ['Temasek Foundation'],
    'Zuraidah Abdullah': ['Temasek Foundation'],
    'Goh Geok Khim': ['Temasek Foundation'],
    'Koo Tsai Kee': ['Temasek Foundation'],
    'Benny Lim': ['Temasek Foundation'],
    'Quek See Tiat': ['Temasek Foundation'],
    'Arif Rachmat': ['Temasek Foundation'],
    'Prof Leo Tan': ['Temasek Foundation'],
    'Tan Soo Nan': ['Temasek Foundation'],
    'Ng Boon Heong': ['Temasek Foundation'],

    // NUHS Directors
    'Yeoh Khay Guan': ['NUHS'],
    'Tan Eng Chye': ['NUHS'],
    'Vincent Chin': ['NUHS'],
    'Mildred Tan': ['NUHS'],
    'Lim Yean Teng': ['NUHS'],
    'Ishak Ismail': ['NUHS'],
    'Deanna Ong': ['NUHS'],
    'Wong Heang Fine': ['NUHS'],
    'James Donovan': ['NUHS'],
    'Yeoh KC': ['NUHS'],

    // CPF Directors
    'Melissa Khoo (CEO)': ['CPF'],
    'Kenny Tan': ['CPF'],
    'Titus Lee': ['CPF'],
    'Tan Hee Teck': ['CPF'],
    'Kohe Hasan': ['CPF'],
    'K Thanaletchimi': ['CPF'],
    'Caryn Lim': ['CPF'],
    'Lai Wei Lin': ['CPF'],
    'Liew Tzu Mi': ['CPF'],
    'Anthony Lim': ['CPF','DBS Group','Capitaland Investment'],
    'Marcus Lim': ['CPF'],
    'Rowena Yeo': ['CPF'],

    // Temasek Directors - already complete
    'Lim Boon Heng': ['Temasek','NTUC Enterprise Coop', 'NTUC Health for Life', 'Philanthropy Asia Limited'],
    'Teo Chee Hean': ['Temasek'],
    'Jenny Lee': ['Temasek','Duke NUS Medical School', 'LKY School of Public Policy'],
    'Ong Pang Thye': ['Temasek','SP Group', 'MOH Holdings'],
    'Jim Hagemann': ['Temasek'],
    'Tan Chee Meng': ['Temasek'],
    'Tan Chong Meng': ['Temasek','NUHS'],
    'Peter Voser': ['Temasek','PSA', 'ABB Ltd', 'IBM Corp'],
    'Geoffrey Wong': ['Temasek'],
    'Jaime Augusto': ['Temasek'],

    // --- GenZero Directors ---
    'Peter Bakker': ['GenZero'],
    'Steve Howard': ['GenZero'],
    'Ruth Nussbaum': ['GenZero'],
    'Alan Thompson': ['GenZero'],
    // Duke NUS Medical School
    'Goh Yew Lin': ['Duke NUS Medical School'],
    'Aaron Thean': ['Duke NUS Medical School'],
    'Fidah Alsagoff': ['Duke NUS Medical School'],
    'Edward G. Buckley': ['Duke NUS Medical School'],
    'Chng Hak-Peng': ['Duke NUS Medical School'],
    'Karen Chong': ['Duke NUS Medical School'],
    'Stacy Choong Hui Hui': ['Duke NUS Medical School'],
    'Mary E Klotman': ['Duke NUS Medical School'],
    'Lee Sze Yeng': ['Duke NUS Medical School'],
    'Andrew Lim': ['65 equity partners','Duke NUS Medical School'],
    'Mak Lye Mun': ['Duke NUS Medical School'],
    'Kenneth Mak': ['NUHS','Duke NUS Medical School'],
    'Ivy Ng Swee Lian': ['Duke NUS Medical School'],
    'Ng Wai Hoe': ['Duke NUS Medical School'],
    'Marie Elaine Teo': ['Duke NUS Medical School'],

    // Inlined merged director -> companies (replaced earlier merge blocks)
    // Olam Group related
    'Lim Ah Doo': ['Olam Group'],
    'Yap Chee Keong': ['Seatrium','Shangri-La Asia','Sembcorp Industries','Singlife Holdings','Olam Group'],
    'Sunny Verghese': ['GenZero','Olam Group'],
    'Tran Phuoc': ['Olam Group'],
    'Ajai Puri': ['Olam Group'],
    'Joerg Wolle': ['Olam Group'],
    'Nagi Hamiyeh': ['Olam Group'],
    'Dinesh Khanna': ['Singtel','Olam Group'],
    'Shuji Kobayashi': ['Olam Group'],
    'Yasuaki Matsuo': ['Olam Group'],

    // Ensign Infosecurity
    'Charles Ng': ['Ensign Infosecurity'],
    'Paul Tan': ['Ensign Infosecurity'],
    'Zong Fu Chua': ['Ensign Infosecurity'],
    'Ah Tuan Tan': ['Ensign Infosecurity'],
    'Minhan Lim': ['Ensign Infosecurity'],
    'Kok Leong Chan': ['Ensign Infosecurity'],
    'Steven Ng': ['Ensign Infosecurity'],
    'Diana Tan': ['Ensign Infosecurity'],

    // Enterprise Singapore
    'Lee Chuan Teck': ['Enterprise Singapore'],
    'Cindy Khoo': ['DSTA','Enterprise Singapore'],
    'Ameera Ashraf': ['Enterprise Singapore'],
    'Cham Hui Fong': ['NUHS','Enterprise Singapore'],
    'Khoo Boo Hor': ['Enterprise Singapore'],
    'Peter Lam': ['Enterprise Singapore'],
    'Cindy Lim': ['Enterprise Singapore'],
    'Lim Ming Yan': ['Enterprise Singapore'],
    'Michael Muller': ['Enterprise Singapore'],
    'Png Cheong Boon': ['Enterprise Singapore'],
    'Png Chin Yee': ['Enterprise Singapore'],
    'Paul Santos': ['Enterprise Singapore'],
    'Sim Feng-Ji': ['Enterprise Singapore'],
    'Satveer Singh Thakral': ['Enterprise Singapore'],
    'Helen Wong': ['Enterprise Singapore','Capitaland Investment'],

    // Seviora Holdings
    'Dilhan Pillay': ['Temasek','Seviora Holdings','Enterprise Singapore'],
    'Gabriel Lim': ['Seviora Holdings','Capitaland Investment'],
    'Jimmy Phoon': ['Seviora Holdings'],
    'Rohit Sipahimalani': ['Seviora Holdings'],
    'Vijay Chandur Advani': ['Seviora Holdings'],
    'Lucas Tran': ['Seviora Holdings'],
    'Timothy Dattels': ['Seviora Holdings'],
    'Chan Wai Ching': ['Seviora Holdings'],
    'John Marren': ['Seviora Holdings'],

    // SP Group related
    'Leong Wai Leng': ['SP Group'],
    'Timothy Chia Chee Ming': ['SP Group'],
    'Lee Kim Shin': ['SIA','SP Group'],
    'Goh Swee Chen': ['SIA','GenZero','SP Group','JTC Corp'],
    'Yaacob Bin Ibrahim': ['SP Group'],
    'Antonio Volpin': ['SP Group'],
    'Ow Foong Pheng': ['URA Singapore','SP Group'],
    'Ching Wei Hong': ['SP Group'],
    'Stanley Huang Tian Guan': ['SP Group'],
    // Newly added SGX Ltd directors
    'Beh Swan Gin': ['SGX Ltd'],
    'Chng Sok Hui': ['SGX Ltd'],
    'Julie Gao': ['SGX Ltd'],
    'Datuk Maimoonah Hussain': ['SGX Ltd'],
    'Stuart Lewis': ['SGX Ltd'],
    'Lim Chin Hu': ['SGX Ltd','ST Engineering'],
    'Lin Huey Ru': ['SGX Ltd'],
    "Claire Perry O'Neill": ['SGX Ltd'],
    'Samuel Tsien': ['SGX Ltd'],
    // Newly added DBS Group directors
    'Tan Su Shan': ['DBS Group'],
    'Olivier Lim': ['DBS Group'],
    'Chng Kai Fong': ['DBS Group'],
    'Bonghan Cho': ['DBS Group'],
    'David Ho': ['DBS Group'],
    'Punita Lal': ['DBS Group'],
    'Judy Lee': ['DBS Group','JTC Corp'],
    'Tham Sai Choy': ['DBS Group'],
    'Chia Song Hwee': ['JTC Corp'],
    'Rachel Eng': ['JTC Corp'],
    'Lee Ghim Ha Jill': ['JTC Corp'],
    'Bernard Menon': ['JTC Corp'],
    'Tan Chin Hwee': ['JTC Corp'],
    'Andrew Kwan': ['JTC Corp'],
    'Mohamad Saiful': ['JTC Corp'],
    // Newly added OCBC Ltd directors
    'Andrew Lee': ['OCBC Ltd'],
    'Chua Kim Chiu': ['OCBC Ltd'],
    'Andrew Khoo': ['OCBC Ltd'],
    'Lee Tih Shih': ['OCBC Ltd'],
    'Lian Wee Cheow': ['OCBC Ltd'],
    'Pramukti Surjaudaja': ['OCBC Ltd'],
    // Newly added Grab Holdings directors
    'Dara Khosrowshahi': ['Grab Holdings'],
    'John Rogers': ['Grab Holdings'],
    'Daniel Yun': ['Grab Holdings'],
    'Steven Tishman': ['Grab Holdings'],
    'Peter Oey': ['Grab Holdings'],
    'Cheryl Goh': ['Grab Holdings'],
    // Newly added Sea Ltd directors
    'forrest Li': ['Sea Ltd'],
    'Gang Ye': ['Sea Ltd'],
    'David Ma': ['Sea Ltd'],
    'David Heng': ['Sea Ltd'],
    'Khoon Hua kuok': ['Sea Ltd'],
    'Silvio Savarese': ['Sea Ltd'],
    // Newly added Keppel Corp directors
    'Danny Teoh': ['Keppel Corp'],
    'Piyush Gupta': ['Keppel Corp'],
    'Shirish Apte': ['Keppel Corp'],
    'Olivier Blum': ['Keppel Corp'],
    'Nee Koon Hean Chua Cheong': ['Keppel Corp'],
    // Newly added ST Engineering directors
    'Neo Gim Huay': ['ST Engineering'],
    'Ng Bee Bee': ['ST Engineering'],
    'Song Su-Min': ['ST Engineering'],
    'Tan Peng Yam': ['ST Engineering'],
    'Chong Shi Hao': ['ST Engineering'],
    'Lien Siaou-Sze': ['ST Engineering'],
    'Kevin Kwok': ['ST Engineering'],
    'Chaly Mah Chee Kheong': ['Capitaland Investment'],
    'Miguel Ko': ['Capitaland Investment'],
    'Judy Hsu': ['Capitaland Investment'],
    'David Su Tuong': ['Capitaland Investment'],
    'Tan Sri Abdul Farid Alias': ['Capitaland Investment'],
    'Belita Ong': ['Capitaland Investment'],
    'Tham Kui Seng': ['Capitaland Investment'],
};



// Mapping of company node id -> public website URL (optional).
// Only the companies you requested are included here; others have no URL for now.
const companyURLs = {
    'Singtel': 'https://www.marketscreener.com/quote/stock/SINGAPORE-TELECOMMUNICATI-6491140/company-governance/',
    '65 equity partners': 'https://www.65equitypartners.com/people/',
    'ABB Ltd': 'https://global.abb/group/en/about/corporate-governance/board-of-directors',
    'BP': 'https://www.bp.com/en/global/corporate/who-we-are/board-and-executive-management/the-board.html',
    'Chevron': 'https://www.chevron.com/who-we-are/leadership',
    'CPF': 'https://www.cpf.gov.sg/member/who-we-are/board-members',
    'DSTA': 'https://www.dsta.gov.sg/who-we-are/dsta-board',
    'Duke NUS Medical School': 'https://www.duke-nus.edu.sg/about/leadership',
    'Ensign Infosecurity': 'https://www.ensigninfosecurity.com/about-ensign/our-leadership',
    'Equinor': 'https://www.equinor.com/about-us/board-of-directors',
    'Enterprise Singapore': 'https://www.enterprisesg.gov.sg/about-us/board-of-directors',
    'GenZero': 'https://genzero.co/team/',
    'GIC': 'https://www.gic.com.sg/who-we-are/board-of-directors/',
    'Haw Par Corp Ltd': 'https://www.hawpar.com/about-us/board',
    'IBM Corp': 'https://www.ibm.com/investor/governance/meet-the-board',
    'IRA Singapore': 'https://www.iras.gov.sg/who-we-are/our-organisation/board-members-and-committees',
    'Keppel Offshore': 'https://www.keppel.com/about-us/our-board/',
    'Jurong Port': 'https://www.jp.com.sg/about-us/leadership/',
    'Kuok Group': 'https://kuokgroup.com.sg/about/',
    'LKY School of Public Policy': 'https://lkyspp.nus.edu.sg/explore-lkyspp/governing-board',
    'Maritime Port Authority Singapore': 'https://www.mpa.gov.sg/who-we-are/about-mpa/board-members?page=1&type=2aeba4dc-152e-46b1-a672-d2b523aaa1ed',
    'Ministry of Dig Dev & Info': 'https://www.mddi.gov.sg/who-we-are/senior-management',
    'MOH Holdings': 'https://www.mohh.com.sg/about-us/our-leadership',
    'Nippon Paint': 'https://www.nipponpaint-holdings.com/en/sustainability/governance/board/',
    'SIA': 'https://www.singaporeair.com/en_UK/sg/about-us/information-for-investors/SIA-Director/',
    'DBS Group': 'https://www.dbs.com/about-us/our-leadership/director.page',

    // New mappings added per your request:
    'NTUC Health for Life': 'https://ntuchealth.sg/about-us/leadership',
    'NTUC LearningHub': 'https://www.ntuclearninghub.com/about-us/board-of-directors',
    'NUHS': 'https://www.nuhs.edu.sg/about-nuhs/our-leadership/nuhs-board-members',
    'Olam Group': 'https://www.olamgroup.com/about-olam/board-of-directors.html',
    'Philanthropy Asia Limited': 'https://philanthropyasiaalliance.org/about-us',
    'PSA': 'https://www.globalpsa.com/bod/',
    'SATS Ltd': 'https://www.sats.com.sg/about-us/leadership-team',
    'URA Singapore': 'https://www.ura.gov.sg/Corporate/About-Us/Who-We-Are/Board-Members',
    'UOL': 'https://www.marketscreener.com/quote/stock/UOL-GROUP-LIMITED-6491133/company-governance/',
    'UOB-Kay Hian': 'https://www.uobkayhian.com/about-us-board.html',
    'UOB Ltd': 'https://www.uobgroup.com/uobgroup/about/management/board-of-directors.page',
    'TotalEnergies': 'https://totalenergies.com/company/identity/governance/board-of-directors',
    'The Straits Trading Company': 'https://www.straitstrading.com.sg/leadership.html',
    'Temasek Foundation': 'https://www.temasekfoundation.org.sg/about-us/leadership',
    'Temasek': 'https://www.temasek.com.sg/en/about-us/our-board',
    'SP Group': 'https://www.spgroup.com.sg/about-us/board-of-directors',
    'Singapore Land Group': 'https://www.singaporeland.com/corporate-profile/board-of-directors/',
    'Singlife Holdings': 'https://singlife.com/en/about-us/leadership-team',
    'SIM': 'https://www.sim.edu.sg/about-sim/discover-sim/corporate-governance',
    // New mappings requested
    'SIA Eng': 'https://www.siaec.com.sg/our_company/board_directors.html',
    'Shell': 'https://www.shell.com/who-we-are/leadership/board-of-directors.html',
    'Shangri-La Asia': 'https://www.shangri-la.com/group/our-story/leadership-team',
    'Seviora Holdings': 'https://www.sevioragroup.com/about',
    'Sembcorp Industries': 'https://www.sembcorp.com/about-us/our-leadership/',
    'Seatrium': 'https://seatrium.com/',
    'SkillsFuture Singapore': 'https://www.ssg.gov.sg/about-us/board-members',
    'SGX Ltd': 'https://www.sgxgroup.com/leadership/board-directors/',
    'Sea Ltd': 'https://www.sea.com/investor/corporategovernance',
    'OCBC Ltd': 'https://www.ocbc.com/group/about-us/our-leadership/board-of-directors.page',
    'Grab Holdings': 'https://investors.grab.com/corporate-governance/board-of-directors/',
    'ST Engineering': 'https://www.stengg.com/en/about-us/board-of-directors/',
    'Keppel Corp': 'https://www.keppel.com/annualreport2022/theme/default/pdf/keppel-corporation-ar-22-board-of-directors.pdf',
    'Capitaland Investment': 'https://www.capitaland.com/en/investment/about-us/board-of-directors.html',
    'JTC Corp': 'https://www.jtc.gov.sg/about-jtc/who-we-are/meet-our-team',
};



if (typeof module !== 'undefined' && module.exports) {
    module.exports = { nodesData, directorCompanies, companyURLs };
}